# Generated by Django 5.0.1 on 2024-01-19 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goal_deadline_alter_subgoal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 13, 51, 32, 753176)),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 13, 51, 32, 753563)),
        ),
    ]
