# Generated by Django 5.0.1 on 2024-01-19 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_goal_deadline_alter_goal_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 14, 53, 2, 27454)),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 14, 53, 2, 27788)),
        ),
    ]
