# Generated by Django 5.0.1 on 2024-02-03 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_goal_progress_alter_goal_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 6, 51, 564739)),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 6, 51, 564739)),
        ),
    ]
