# Generated by Django 5.0.1 on 2024-02-16 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_goal_reward_goal_measurable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='relevant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 14, 15, 57, 744688)),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 14, 15, 57, 744688)),
        ),
    ]
