# Generated by Django 5.0.1 on 2024-02-16 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_goal_relevant_alter_goal_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 15, 41, 33, 561651)),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 15, 41, 33, 561651)),
        ),
    ]
